<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HbpSoft" failures="1" tests="9" name="Default test" time="39.866" errors="0" timestamp="2024-03-21T12:14:51 IST">
  <testcase classname="com.machines.Ping_Status.PP_Machines" name="pp1" time="3.877"/>
  <testcase classname="com.machines.Ping_Status.PP_Machines" name="pp2" time="6.712">
    <failure type="java.lang.AssertionError" message="did not expect [0] but found [0]">
      <![CDATA[java.lang.AssertionError: did not expect [0] but found [0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at org.testng.Assert.assertNotEquals(Assert.java:1535)
at com.machines.Ping_Status.PP_Machines.connect(PP_Machines.java:105)
at com.machines.Ping_Status.PP_Machines.pp2(PP_Machines.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- pp2 -->
  <testcase classname="com.machines.Ping_Status.PP_Machines" name="pp3v5" time="3.698"/>
  <testcase classname="com.machines.Ping_Status.PP_Machines" name="pp4v5" time="3.721"/>
  <testcase classname="com.machines.Ping_Status.PP_Machines" name="pp4v15" time="3.702"/>
  <testcase classname="com.machines.Ping_Status.PP_Machines" name="pp5v5" time="6.837"/>
  <testcase classname="com.machines.Ping_Status.PP_Machines" name="pp5v15" time="3.697"/>
  <testcase classname="com.machines.Ping_Status.PP_Machines" name="pp7v5" time="3.773"/>
  <testcase classname="com.machines.Ping_Status.PP_Machines" name="pp7v15" time="3.814"/>
</testsuite> <!-- Default test -->
